name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set Docker image tag
        id: set-image-tag
        run: echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: build/libs/*.jar

      - name: Build and push Docker image
        run: |
          docker build -t kapil4457/expense-tracker-user-service:${{ github.sha }} .
          docker push kapil4457/expense-tracker-user-service:${{ github.sha }}

  update-k8s-manifests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v5
        with:
          repository: kapil4457/Expense-Tracker---Configuration
          token: ${{ secrets.K8S_REPO_TOKEN }}
          path: .

      - name: Update Kubernetes manifest
        run: |
          IMAGE_TAG=${{ needs.build-image.outputs.IMAGE_TAG }}
          sed -i "s|image: kapil4457/expense-tracker-user-service:.*|image: kapil4457/expense-tracker-user-service:${IMAGE_TAG}|g" argocd-k8s-manifests/user-service/deployment.yaml

      - name: Commit and push changes
        run: |
          cd argocd-k8s-manifests
          git config user.name "Kapil Soni"
          git config user.email "kapilsoni54768161@gmail.com"
          git add .
          git commit -m "Update user-service image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push
